# Generated by Django 3.2.9 on 2021-11-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('sample_type', models.CharField(blank=True, choices=[('wet sediment', 'Wet Sediment'), ('dry sediment', 'Dry Sediment'), ('water', 'Water'), ('water & solvent', 'Water & Solvent'), ('extract', 'Extract')], max_length=100)),
                ('extraction_method', models.CharField(blank=True, choices=[('soxhlet', 'Soxhlet'), ('saponification', 'Saponification'), ('sepratory funnel', 'Sepratory Funnel'), ('roller', 'Roller'), ('other', 'Other')], max_length=100)),
                ('sample_cleanup', models.CharField(blank=True, choices=[('silica gel', 'Silica Gel'), ('gpc', 'GPC'), ('purge & trap', 'Purge & Trap'), ('none', 'None')], max_length=100)),
                ('analysis_instrumentation', models.CharField(blank=True, choices=[('gc/ms', 'GC/MS'), ('gc/fid', 'GC/FID'), ('spectrophotometer', 'Spectrophotometer'), ('iatroscan', 'Iatroscan'), ('lc', 'LC'), ('none', 'None')], max_length=100)),
                ('analysis_pah', models.BooleanField(default=False)),
                ('analysis_alkanes', models.BooleanField(default=False)),
                ('analysis_phenols', models.BooleanField(default=False)),
                ('analysis_tph', models.BooleanField(default=False)),
                ('analysis_btex', models.BooleanField(default=False)),
                ('log_comments', models.TextField()),
            ],
        ),
    ]
